# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addrowdialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog, form_items=[]):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.form_items = form_items
        self.add_row_but = QtWidgets.QDialogButtonBox(Dialog)
        self.add_row_but.setGeometry(QtCore.QRect(30, 260, 341, 32))
        self.add_row_but.setOrientation(QtCore.Qt.Horizontal)
        self.add_row_but.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.add_row_but.setObjectName("add_row_but")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 10, 331, 241))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        # 动态添加表单
        for i, item in enumerate(form_items):
            setattr(self, f"label_{item}", QtWidgets.QLabel(self.formLayoutWidget))
            getattr(self, f"label_{item}").setObjectName(f"label_{item}")
            self.formLayout.setWidget(i, QtWidgets.QFormLayout.LabelRole, getattr(self, f"label_{item}"))
            setattr(self, f"lineEdit_{item}", QtWidgets.QLineEdit(self.formLayoutWidget))
            getattr(self, f"lineEdit_{item}").setObjectName(f"lineEdit_{item}")
            self.formLayout.setWidget(i, QtWidgets.QFormLayout.FieldRole, getattr(self, f"lineEdit_{item}"))

        self.retranslateUi(Dialog)
        self.add_row_but.accepted.connect(Dialog.accept)  # type: ignore
        self.add_row_but.rejected.connect(Dialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        for i, item in enumerate(self.form_items):
            getattr(self, f"label_{item}").setText(_translate("Dialog", item))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
